"""Add ModelResponses

Revision ID: 6ac0fa3c754c
Revises: ea0820a5844f
Create Date: 2026-01-11 15:29:22.218744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ac0fa3c754c'
down_revision: Union[str, Sequence[str], None] = 'ea0820a5844f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_responses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_json_store_data_gin', 'model_responses', ['data'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_json_store_data_gin', table_name='model_responses', postgresql_using='gin')
    op.drop_table('model_responses')
    # ### end Alembic commands ###
