"""change created_at and updated_at

Revision ID: 9b22cbd2ef31
Revises: 6ac0fa3c754c
Create Date: 2026-01-11 19:30:19.748967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b22cbd2ef31'
down_revision: Union[str, Sequence[str], None] = '6ac0fa3c754c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('admin_users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('ai_models', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ai_models', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('model_responses', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('model_responses', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_responses', 'updated_at')
    op.drop_column('model_responses', 'created_at')
    op.drop_column('ai_models', 'updated_at')
    op.drop_column('ai_models', 'created_at')
    op.drop_column('admin_users', 'updated_at')
    op.drop_column('admin_users', 'created_at')
    # ### end Alembic commands ###
